### ISSUE TITLE
String error for parsed text while importing PDF file into database

### ISSUE THREAD

**Issue by gerbsen** [meine-stadt-transparent/meine-stadt-transparent#167]
I'm trying to import the [PDF](https://ratsinfo.leipzig.de/bi/oparl/1.0/download.asp?dtyp=130&id=1221732) which is a quite long one. 

```
Downloading https://ratsinfo.leipzig.de/bi/oparl/1.0/download.asp?dtyp=130&id=1221732
INFO:importer.oparl_helper:Downloading https://ratsinfo.leipzig.de/bi/oparl/1.0/download.asp?dtyp=130&id=1221732
Extracting text from PDF for file 3678 (1221732.pdf)
INFO:importer.oparl_helper:Extracting text from PDF for file 3678 (1221732.pdf)
Extracting locations from PDF for file 3678 (1221732.pdf)
INFO:importer.oparl_helper:Extracting locations from PDF for file 3678 (1221732.pdf)
Traceback (most recent call last):
  File "/app/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\x89\\xF0\\x9D...' for column 'parsed_text' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/app/mainapp/management/commands/import.py", line 19, in handle
    oparl_cli.from_userinput(options["cityname"], options["mirror"])
  File "/app/importer/oparl_cli.py", line 65, in from_userinput
    self.run_importer(ags, importer, liboparl_body)
  File "/app/importer/oparl_cli.py", line 130, in run_importer
    importer.list_batched(liboparl_body.get_paper, importer.paper)
  File "/app/importer/oparl_import.py", line 44, in list_batched
    fn(item)
  File "/app/importer/oparl_objects.py", line 135, in paper
    libobject, Paper, self.paper_core, self.paper_embedded
  File "/app/importer/oparl_helper.py", line 129, in process_object
    associates_changed = embedded(libobject, outer_object)
  File "/app/importer/oparl_objects.py", line 147, in paper_embedded
    paper.main_file = self.file(libobject.get_main_file())
  File "/app/importer/oparl_objects.py", line 514, in file
    file.save()
  File "/app/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/app/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 812, in _save_table
    forced_update)
  File "/app/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 861, in _do_update
    return filtered._update(values) > 0
  File "/app/.venv/lib/python3.5/site-packages/django/db/models/query.py", line 712, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/app/.venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/app/.venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/app/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/app/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/app/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/app/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/app/.venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\x89\\xF0\\x9D...' for column 'parsed_text' at row 1")
```

**Comment by konstin** [comment]
This should have been fixed by https://github.com/meine-stadt-transparent/meine-stadt-transparent/commit/17279672518e83339ed8f37dbf8564b80b80ac07, but if you're using a database that was created before that commit it has kept the old character set and collation. 

I'm currently making some significant changes to the importer, which will make it much more reliable with big cc egov cities such as Leipzig. I'd ask for a bit of patience until that's finished; I'll report back once I've verified that the existing oparl cities work properly.

**Comment by konstin** [comment]
The current status is that the import for Leipzig technically works on my local branch. I've started fixing some quirks with cc-egov's implementation. What's still missing is:

 * `GEOEXTRACT_DEFAULT_CITY` should be passed to the initial file analysis
 * Test that Jülich still works and that Leipzig works with docker
 * The cron job needs to be changed
 * The file import needs a unit test
 * The file import is unrealistically slow for Leipzig because the location extraction is slow. That needs to be investigated and fixed.
 * Likely something with travis ci that needs to be changed.

I'd like to fix all of the above properly before setting up the retrying the setup, which will unfortunately take a bit of time.
