### ISSUE TITLE
HTTP 500 after email confirmation  -redacted-

### ISSUE THREAD

**Issue by ubergesundheit** [meine-stadt-transparent/meine-stadt-transparent#486]
After clicking the confirmation button on the page behind the confirmation link, I got a cute cat. I think confirmation worked though.

<details>

<summary>Relevant server logs</summary>

```
2020-10-09 15:26:19,938 Internal Server Error: /accounts/confirm-email/MQ:1kQsPW:-redacted--w3GXGQ/
Traceback (most recent call last):
  File "/app/.venv/lib/python3.7/site-packages/django/shortcuts.py", line 131, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/app/.venv/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/app/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'True' not found. 'True' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 36, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/app/.venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.venv/lib/python3.7/site-packages/allauth/account/views.py", line 301, in post
    return redirect(redirect_url)
  File "/app/.venv/lib/python3.7/site-packages/django/shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/app/.venv/lib/python3.7/site-packages/django/shortcuts.py", line 137, in resolve_url
    if '/' not in to and '.' not in to:
TypeError: argument of type 'bool' is not iterable
10.0.0.152 - - [09/Oct/2020:15:26:19 +0200] "POST /accounts/confirm-email/MQ:1kQsPW:-redacted--w3GXGQ/ HTTP/1.0" 500 5049 "https://meine-stadt-transparent.codeformuenster.org/accounts/confirm-email/MQ:1kQsLc:-redacted-/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1"
```

</details>

**Comment by konstin** [comment]
I saw the error in sentry too, but when I try to reproduce this, (created a new account, clicked the confirmation link), everything worked fine. Do you have an idea what special steps are required to reproduce the issue?

**Comment by ubergesundheit** [comment]
I did the following:

- Registered an account with my laptop
- Subscribed to some topics
- Then with my mobile phone, I opened the link in the mail and clicked the confirmation button

maybe this is related to using multiple devices?
